### ISSUE TITLE
Páginas internas (anúncio)

### ISSUE THREAD

**Issue by bconfortin** [amandaalouise/ProjetoAndroid#6]
Se clica na Sophia, vai pro Pimpolho. Acontece em vários anúncios

**Comment by amandaalouise** [comment]
Já sei a causa, vou resolver.

**Comment by amandaalouise** [comment]
Esse erro acontecia quando um mesmo anúncio era enviado mais de uma vez. Causando um bug no sistema.

Resolvi desabilitando o botão após o clique, para evitar que isso ocorra de novo.
Caso aconteça de novo, me avise.
